"""Auto-generated hierarchical index — ``index.md`` + ``log.md`` (Group C).

Regenerates two human-browsable overview documents from the current
active block corpus:

* ``index.md`` — **hierarchical**: blocks grouped by *category* (the
  corpus source label — decisions, tasks, projects, ...) and, within
  each category, by *kind* (the block-id prefix — ``D``, ``T``,
  ``PRJ``, ``SIG``, ...). Categories, kinds and blocks are all emitted
  in a stable sorted order.
* ``log.md`` — **chronological**: every block on one flat timeline,
  oldest first, with undated blocks listed last in a separate section.

Both files are pure projections of the block corpus: regenerating them
without corpus changes is byte-for-byte idempotent (no timestamps, no
counters that depend on run time or iteration order). Blocks are
enumerated through the backend-aware
:func:`mind_mem.storage.iter_active_blocks` primitive, so a Postgres
workspace indexes the store's blocks of record, not the (empty) local
Markdown corpus.

Stdlib only. Writes are atomic (``tmp`` + ``os.replace``) and skipped
entirely when the rendered content matches what is already on disk.

Usage::

    from mind_mem.memory_index import generate_index
    result = generate_index("/path/to/workspace")

or via the CLI::

    mm index [--out-dir DIR]
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass, field
from typing import Any

__all__ = [
    "INDEX_FILENAME",
    "LOG_FILENAME",
    "IndexResult",
    "generate_index",
]

_log = logging.getLogger("mind_mem.memory_index")

INDEX_FILENAME = "index.md"
LOG_FILENAME = "log.md"

# Marker comment so humans (and future tooling) know the files are
# generated projections, not hand-maintained sources of truth.
_GENERATED_MARKER = "<!-- auto-generated by `mm index` — do not edit; regenerate from the block corpus -->"

# block-id prefix: everything before the first "-" (e.g. D-2026...-001 -> D).
_ID_PREFIX_RE = re.compile(r"^([A-Za-z]+)-")

# YYYYMMDD embedded in the canonical id format PREFIX-YYYYMMDD-NNN.
_ID_DATE_RE = re.compile(r"^[A-Za-z]+-(\d{8})(?:-|$)")

# ISO date (YYYY-MM-DD) anywhere in a Date-ish field value.
_ISO_DATE_RE = re.compile(r"\b(\d{4}-\d{2}-\d{2})\b")

# Fields tried, in order, for a one-line block summary.
_SUMMARY_FIELDS = ("Statement", "Title", "Name", "Subject", "content")

_MAX_SUMMARY_CHARS = 120


@dataclass(frozen=True)
class IndexResult:
    """Outcome of one :func:`generate_index` run."""

    index_path: str
    log_path: str
    block_count: int
    index_changed: bool
    log_changed: bool
    category_counts: dict[str, int] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "index_path": self.index_path,
            "log_path": self.log_path,
            "block_count": self.block_count,
            "index_changed": self.index_changed,
            "log_changed": self.log_changed,
            "category_counts": dict(self.category_counts),
        }


# ---------------------------------------------------------------------------
# Block projection helpers
# ---------------------------------------------------------------------------


def _block_category(block: dict[str, Any]) -> str:
    """Category = corpus source label; fall back to the source file stem."""
    label = block.get("_source_label")
    if isinstance(label, str) and label.strip():
        return label.strip()
    src = block.get("_source_file")
    if isinstance(src, str) and src.strip():
        stem = os.path.splitext(os.path.basename(src))[0]
        return stem.lower()
    return "uncategorized"


def _block_kind(block: dict[str, Any]) -> str:
    """Kind = block-id prefix (``D``, ``T``, ``PRJ``, ...)."""
    m = _ID_PREFIX_RE.match(str(block.get("_id", "")))
    return m.group(1).upper() if m else "OTHER"


def _block_date(block: dict[str, Any]) -> str:
    """Best-effort ISO date for a block, or "" when undated.

    Priority: explicit ``Date``/``Created`` field (first ISO date in the
    value) → the YYYYMMDD embedded in the canonical block-id format.
    """
    for key in ("Date", "Created"):
        v = block.get(key)
        if isinstance(v, str):
            m = _ISO_DATE_RE.search(v)
            if m:
                return m.group(1)
    m2 = _ID_DATE_RE.match(str(block.get("_id", "")))
    if m2:
        raw = m2.group(1)
        return f"{raw[0:4]}-{raw[4:6]}-{raw[6:8]}"
    return ""


def _block_summary(block: dict[str, Any]) -> str:
    """One-line, whitespace-collapsed summary of a block (may be "")."""
    for key in _SUMMARY_FIELDS:
        v = block.get(key)
        if isinstance(v, str) and v.strip():
            text = " ".join(v.split())
            if len(text) > _MAX_SUMMARY_CHARS:
                text = text[: _MAX_SUMMARY_CHARS - 1].rstrip() + "…"
            return text
    return ""


def _sort_key(block: dict[str, Any]) -> tuple[str, str]:
    """Deterministic (date, id) ordering; undated blocks sort last."""
    date = _block_date(block)
    return (date or "9999-99-99", str(block.get("_id", "")))


# ---------------------------------------------------------------------------
# Renderers (pure functions of the block list — no clocks, no randomness)
# ---------------------------------------------------------------------------


def _index_entry(block: dict[str, Any]) -> str:
    bid = str(block.get("_id", "?"))
    date = _block_date(block)
    summary = _block_summary(block)
    parts = [f"- **[{bid}]**"]
    if date:
        parts.append(f"({date})")
    if summary:
        parts.append(f"— {summary}")
    src = block.get("_source_file")
    if isinstance(src, str) and src.strip():
        parts.append(f"· (`{src}`)")
    return " ".join(parts)


def _render_index(blocks: list[dict[str, Any]]) -> str:
    """Render the hierarchical ``index.md`` body (category → kind → blocks)."""
    tree: dict[str, dict[str, list[dict[str, Any]]]] = {}
    for b in blocks:
        tree.setdefault(_block_category(b), {}).setdefault(_block_kind(b), []).append(b)

    lines: list[str] = [
        _GENERATED_MARKER,
        "",
        "# Memory Index",
        "",
        f"Active blocks: **{len(blocks)}** across **{len(tree)}** categories.",
        "",
    ]
    for category in sorted(tree):
        kinds = tree[category]
        cat_total = sum(len(v) for v in kinds.values())
        lines.append(f"## {category} ({cat_total})")
        lines.append("")
        for kind in sorted(kinds):
            members = sorted(kinds[kind], key=_sort_key)
            lines.append(f"### {kind} ({len(members)})")
            lines.append("")
            lines.extend(_index_entry(b) for b in members)
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_log(blocks: list[dict[str, Any]]) -> str:
    """Render the chronological ``log.md`` body (oldest first)."""
    dated = sorted((b for b in blocks if _block_date(b)), key=_sort_key)
    undated = sorted((b for b in blocks if not _block_date(b)), key=_sort_key)

    lines: list[str] = [
        _GENERATED_MARKER,
        "",
        "# Memory Log",
        "",
        f"Active blocks: **{len(blocks)}** ({len(dated)} dated, {len(undated)} undated).",
        "",
    ]
    if dated:
        lines.append("## Timeline")
        lines.append("")
        for b in dated:
            bid = str(b.get("_id", "?"))
            summary = _block_summary(b)
            row = f"- {_block_date(b)} — **[{bid}]** ({_block_category(b)})"
            if summary:
                row += f": {summary}"
            lines.append(row)
        lines.append("")
    if undated:
        lines.append("## Undated")
        lines.append("")
        for b in undated:
            bid = str(b.get("_id", "?"))
            summary = _block_summary(b)
            row = f"- **[{bid}]** ({_block_category(b)})"
            if summary:
                row += f": {summary}"
            lines.append(row)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Filesystem
# ---------------------------------------------------------------------------


def _write_if_changed(path: str, content: str) -> bool:
    """Atomically write *content* to *path*; return True when it changed.

    Skips the write entirely when the on-disk bytes already match, so a
    no-op regeneration does not touch mtimes (keeps ``mm index`` safe to
    run from cron / daemon loops without triggering file-watchers).
    """
    try:
        with open(path, encoding="utf-8") as fh:
            if fh.read() == content:
                return False
    except (OSError, UnicodeDecodeError):
        pass  # missing or unreadable — (re)write below
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(content)
    os.replace(tmp, path)  # atomic on POSIX + Windows
    return True


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_index(
    workspace: str,
    config: dict[str, Any] | None = None,
    *,
    out_dir: str | None = None,
) -> IndexResult:
    """Regenerate ``index.md`` + ``log.md`` for *workspace*.

    Args:
        workspace: Path to the mind-mem workspace root.
        config:    Parsed ``mind-mem.json`` dict, or ``None`` to
                   auto-load (same contract as ``iter_active_blocks``).
        out_dir:   Directory the two files are written to. Defaults to
                   the workspace root.

    Returns:
        :class:`IndexResult` with the written paths, block/category
        counts, and per-file changed flags (``False`` = content was
        already up to date, nothing was touched).

    Deterministic + idempotent: output depends only on the active block
    corpus; consecutive runs over an unchanged corpus produce identical
    bytes and report ``index_changed=log_changed=False``.
    """
    # Lazy import mirrors the rest of the feature layer — keeps
    # ``import mind_mem.memory_index`` free of recall/parse cost.
    from .storage import iter_active_blocks

    blocks = iter_active_blocks(workspace, config=config)

    target = os.path.realpath(out_dir) if out_dir else os.path.realpath(workspace)
    os.makedirs(target, exist_ok=True)
    index_path = os.path.join(target, INDEX_FILENAME)
    log_path = os.path.join(target, LOG_FILENAME)

    index_changed = _write_if_changed(index_path, _render_index(blocks))
    log_changed = _write_if_changed(log_path, _render_log(blocks))

    counts: dict[str, int] = {}
    for b in blocks:
        cat = _block_category(b)
        counts[cat] = counts.get(cat, 0) + 1

    result = IndexResult(
        index_path=index_path,
        log_path=log_path,
        block_count=len(blocks),
        index_changed=index_changed,
        log_changed=log_changed,
        category_counts=dict(sorted(counts.items())),
    )
    _log.info(
        "memory_index_generated workspace=%s blocks=%d index_changed=%s log_changed=%s",
        workspace,
        result.block_count,
        index_changed,
        log_changed,
    )
    return result
