#!/usr/bin/env bash
# docs-alignment-hook.sh — Git pre-commit step to refresh derived doc counts.
#
# The alignment claims (test-function count, MCP tool count, CI matrix, ...) are
# CACHES of numbers the tree already knows: scripts/alignment_authorities.py
# derives each one by walking the source. So a commit that adds a test makes a
# doc claim stale by arithmetic, not by anyone's mistake -- and the
# `check_docs_alignment` CI job then goes red for whoever pushes next.
#
# Measured cost of leaving it manual: the gate was already red at aa3db0b
# (authority 11,061 vs claimed 11,026), was refreshed at 46b334e, and went red
# again at d860250 -- twice inside one hour, from three different seats, none of
# whom touched a doc. A number that drifts every time anyone adds a test is a
# number that has to be regenerated by the commit, not remembered by the author.
#
# Same contract as anatomy-hook.sh: regenerate, stage what changed, never block.
# Deliberately advisory (exit 0 on checker failure) -- a docs cache going stale
# must not wedge a commit, and CI is still the enforcing gate.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." 2>/dev/null && pwd)" \
  || ROOT_DIR="$(git rev-parse --show-toplevel)"

SCRIPT="$ROOT_DIR/scripts/check_docs_alignment.py"
[ -f "$SCRIPT" ] || exit 0

# Only run when something OTHER than the alignment targets is staged, so the
# hook cannot loop on its own output.
staged=$(git diff --cached --name-only --diff-filter=ACMR \
  | grep -vE '^(README\.md|CLAUDE\.md|docs/governance\.md)$' || true)
[ -z "$staged" ] && exit 0

cd "$ROOT_DIR"
PY="$(command -v python3.12 || command -v python3 || true)"
[ -n "$PY" ] || exit 0
"$PY" "$SCRIPT" --fix >/dev/null 2>&1 || exit 0

for f in README.md CLAUDE.md docs/governance.md; do
  if [ -f "$f" ] && ! git diff --quiet -- "$f" 2>/dev/null; then
    git add "$f"
  fi
done

exit 0
